name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # This is crucial for creating releases and uploading assets

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Verify workspace structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Assets directory (if exists):"
          ls -la assets || echo "Assets directory not found"

      - name: Verify assets directory
        run: |
          ls -la assets/icons/win
          ls -la assets/icons/mac
          ls -la assets/icons/png

      - name: Build Windows app
        run: npx electron-builder --win --${{ matrix.arch }} --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist directory contents
        run: dir dist

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: dist/*-${{ matrix.arch }}.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Verify workspace structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Assets directory (if exists):"
          ls -la assets || echo "Assets directory not found"

      - name: Verify assets directory
        run: |
          ls -la assets/icons/win
          ls -la assets/icons/mac
          ls -la assets/icons/png

      - name: Build Linux app
        run: npx electron-builder --linux --${{ matrix.arch }} --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist directory contents
        run: ls -la dist/

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: dist/*.AppImage
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Verify workspace structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Assets directory (if exists):"
          ls -la assets || echo "Assets directory not found"

      - name: Verify assets directory
        run: |
          ls -la assets/icons/win
          ls -la assets/icons/mac
          ls -la assets/icons/png

      - name: Build macOS app
        run: npx electron-builder --mac --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List dist directory contents
        run: ls -la dist/

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: dist/*-*.dmg
          if-no-files-found: error

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: PixelMuse ${{ steps.get_version.outputs.VERSION }}
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.AppImage
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 